#!/bin/sh
#
# Copyright (C) 2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh

board_config_update

board=$(cat /proc/device-tree/model)

case "$board" in
    *"AX6"*)
        ucidef_set_led_netdev "wan" "WAN" "ax6:blue:network" "eth1"
        ;;
    *)
	    ;;
esac

board_config_flush

exit 0
