#!/bin/sh
#
# Copyright (c) 2015 The Linux Foundation. All rights reserved.
# Copyright (c) 2011-2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh
. /lib/ipq806x.sh
. /lib/functions/system.sh

board_config_update

board=$(cat /proc/device-tree/model)


find_mmc_part() {
	local DEVNAME PARTNAME

	if grep -q "$1" /proc/mtd; then
		echo "" && return 0
	fi

	for DEVNAME in /sys/block/mmcblk0/mmcblk*p*; do
		PARTNAME=$(grep PARTNAME ${DEVNAME}/uevent | cut -f2 -d'=')
		[ "$PARTNAME" = "$1" ] && echo "/dev/$(basename $DEVNAME)" && return 0
	done
}



case "$board" in
	*AX6* |\
	*AX3600*)
		ucidef_set_interfaces_lan_wan "eth2 eth3 eth4" "eth1"
		;;
	*RT5000W*)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4" "eth0"
		;;
	*MF269*)
		ucidef_set_interfaces_lan_wan "eth0" "eth1"
		mac=$(mtd_get_mac_binary mac 0x0)
		ucidef_set_interface_macaddr "lan" "$(macaddr_add $mac 1)"
		ucidef_set_interface_macaddr "wan" "$mac"
		;;
	*)
		echo "Unsupported hardware. Network interfaces not intialized"
		;;
esac



board_config_flush

exit 0
