#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org 

START=11

. /lib/functions.sh

set_timezone_from_countrycode() {
	cc=`nvram get CountryCode`

    if [ -z "$cc" ]; then
        tz="UTC"
    else
        tz=`uci -q get country_mapping.$cc.timezone`
        [ -z "$tz" ] && tz="UTC"
    fi

	echo $tz > /tmp/TZ
	# update uci config. config_set doesn't work >_<
	# config_set $1 timezone $tz
	uci set system.@system[0].timezone="$tz"
	uci commit system
}


timezone_config() {
	local cfg="$1"
	local idx
	local timezone

    initted=`uci -q get xiaoqiang.common.INITTED`
	# "timezoneindex" exists indicates it was manually changed from web admin interface.
	# Apply the uci timezone config if timezoneindex exist.
	# Otherwise use timezone from country code.
	config_get idx "$cfg" timezoneindex

    #set timezone by CountryCode if not set by mannual and not inited
	if [ -z "$idx" -o "$initted" != "YES" ]; then
		set_timezone_from_countrycode $cfg
	else
		config_get timezone "$cfg" timezone 'UTC'
		echo "$timezone" > /tmp/TZ
	fi
	# apply timezone to kernel
	date -k
}


start() {
	config_load system
    config_foreach timezone_config system
}
