#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=10

#USE_PROCD=1

start() {
	xqled sys_booting
	uci set luci.main.lang='fr'
	uci set luci.languages.en='French'
	uci commit luci
	return 0
}

stop() {
	return 0
}
