#!/bin/sh /etc/rc.common
#


START=99

start() {	
	xt_enabled="$(uci get firewall.@defaults[0].fullcone)"
        /etc/init.d/firewall stop   > /dev/null
	if [ "$xt_enabled" -eq 1 ]; then
          modprobe xt_FULLCONENAT
	else
          rmmod xt_FULLCONENAT
	fi
  	/etc/init.d/firewall start  > /dev/null     
}

stop ()
{	/etc/init.d/firewall stop  > /dev/null
	rmmod xt_FULLCONENAT
	/etc/init.d/firewall start > /dev/null
}
