src/gz reboot_core http://downloads.lede-project.org/releases/17.01-SNAPSHOT/targets/ipq807x/generic/packages
src/gz reboot_base http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/aarch64_cortex-a53+crypto/base
src/gz reboot_luci http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/aarch64_cortex-a53+crypto/luci
src/gz reboot_packages http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/aarch64_cortex-a53+crypto/packages
src/gz reboot_routing http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/aarch64_cortex-a53+crypto/routing
src/gz reboot_telephony http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/aarch64_cortex-a53+crypto/telephony
